# -*- makefile -*-
#
# GCC specific definitions and actions
#

GCC_VERSION := $(shell $(CC) -dumpfullversion -dumpversion)
GCC_MAJOR_VERSION := $(word 1,$(subst ., ,$(GCC_VERSION)))
GCC_MINOR_VERSION := $(word 2,$(subst ., ,$(GCC_VERSION)))

